title: MoneyBay - Ứng Dụng Quản Lý Chi Tiêu Thông Minh
description: > # this means to ignore newlines until "baseurl:"
  MoneyBay - Ứng dụng quản lý chi tiêu cá nhân hàng đầu Việt Nam. Theo dõi chi tiêu, 
  lập ngân sách, tiết kiệm và đầu tư thông minh. Giúp bạn kiểm soát tài chính và 
  đạt được mục tiêu tài chính một cách dễ dàng.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.moneybay.app" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: MoneyBay Team # add your name
author-img: moneybay-logo.jpg # add your photo
about-author: MoneyBay - Ứng dụng quản lý tài chính cá nhân thông minh, giúp bạn theo dõi chi tiêu, lập ngân sách, tiết kiệm và đầu tư hiệu quả. Đạt được tự do tài chính với MoneyBay. # add description
social-twitter: moneybayapp # add your Twitter handle
social-facebook: moneybay.app # add your Facebook handle
# social-github: moneybay # add your Github handle
# social-linkedin: moneybay-app # add your Linkedin handle
social-email: vutas.studio@gmail.com # add your Email address

# Disqus
discus-identifier: moneybay-blog # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
